-- AlterTable
ALTER TABLE "users" ADD COLUMN     "additional_links" TEXT[],
ADD COLUMN     "bio" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "experience" TEXT,
ADD COLUMN     "github_link" TEXT,
ADD COLUMN     "languages" TEXT,
ADD COLUMN     "linkedin_link" TEXT,
ADD COLUMN     "other_links" TEXT,
ADD COLUMN     "portfolio_link" TEXT,
ADD COLUMN     "profession" TEXT,
ADD COLUMN     "profile_picture" TEXT,
ADD COLUMN     "province" TEXT,
ADD COLUMN     "resume_upload_link" TEXT,
ADD COLUMN     "twitter_link" TEXT;
